import { describe, expect, it } from "vitest";
import {
  buildCatalog,
  renderRuntimeCatalog
} from "../lib/catalog.mjs";

const manifest = Object.freeze({
  status: "complete",
  family: "official-spiral",
  generatorVersion: "official-spiral-v1",
  evaluatorVersion: "duel-fair-v3",
  startSeed: 1,
  count: 4,
  v3FeatureVersion: "duel-fair-v3-features-1",
  v3PolicyVersion: "duel-fair-v3",
  v3ProfileHash: "profile-hash"
});

const record = ({
  candidateIndex,
  seed,
  canonicalSymmetryHash,
  overallScore,
  boardHash = `board-${seed}`
}) => ({
  candidateIndex,
  seed,
  generatorFamily: "official-spiral",
  generatorVersion: "official-spiral-v1",
  evaluatorVersion: "duel-fair-v3",
  boardHash,
  canonicalSymmetryHash,
  status: "ranked",
  invalidCodes: [],
  overallScore,
  scores: {
    fairness: overallScore + 1,
    quality: overallScore - 1,
    interest: 50
  },
  tags: [`seed:${seed}`]
});

const records = [
  record({ candidateIndex: 0, seed: 10, canonicalSymmetryHash: "same", overallScore: 80 }),
  record({ candidateIndex: 1, seed: 20, canonicalSymmetryHash: "second", overallScore: 90 }),
  record({ candidateIndex: 2, seed: 30, canonicalSymmetryHash: "same", overallScore: 95 }),
  record({ candidateIndex: 3, seed: 40, canonicalSymmetryHash: "third", overallScore: 70 })
];

describe("duel fair catalog publisher", () => {
  it("keeps the best canonical representative and ranks by overall score", () => {
    const catalog = buildCatalog({
      catalogId: "duel-fair-official-v1",
      runId: "catalog-fixture",
      manifest,
      records,
      size: 2
    });

    expect(catalog).toMatchObject({
      id: "duel-fair-official-v1",
      generator: {
        boardConfigId: "standard-official-spiral",
        family: "official-spiral",
        version: "official-spiral-v1"
      },
      evaluator: {
        version: "duel-fair-v3",
        identity: {
          featureVersion: "duel-fair-v3-features-1",
          policyVersion: "duel-fair-v3",
          profileHash: "profile-hash"
        }
      },
      source: {
        runId: "catalog-fixture",
        startSeed: 1,
        count: 4
      },
      selection: {
        method: "top-overall-distinct-canonical-v1",
        size: 2
      }
    });
    expect(catalog.entries.map((entry) => entry.seed)).toEqual([30, 20]);
    expect(catalog.entries.map((entry) => entry.rank)).toEqual([1, 2]);
    expect(catalog.entries[0]).toMatchObject({
      boardHash: "board-30",
      canonicalSymmetryHash: "same",
      overallScore: 95,
      scores: { fairness: 96, quality: 94, interest: 50 },
      tags: ["seed:30"]
    });
  });

  it("resolves equal scores by lower seed", () => {
    const tied = [
      record({ candidateIndex: 0, seed: 50, canonicalSymmetryHash: "fifty", overallScore: 90 }),
      record({ candidateIndex: 1, seed: 40, canonicalSymmetryHash: "forty", overallScore: 90 })
    ];

    const catalog = buildCatalog({
      catalogId: "duel-fair-official-v1",
      runId: "catalog-fixture",
      manifest: { ...manifest, count: 2 },
      records: tied,
      size: 2
    });

    expect(catalog.entries.map((entry) => entry.seed)).toEqual([40, 50]);
  });

  it("ignores unranked records", () => {
    const catalog = buildCatalog({
      catalogId: "duel-fair-official-v1",
      runId: "catalog-fixture",
      manifest,
      records: [
        ...records,
        { candidateIndex: 4, seed: 99, status: "invalid", overallScore: null }
      ],
      size: 2
    });

    expect(catalog.entries.map((entry) => entry.seed)).toEqual([30, 20]);
  });

  it("renders a compact deterministic runtime module", () => {
    const catalog = buildCatalog({
      catalogId: "duel-fair-official-v1",
      runId: "catalog-fixture",
      manifest,
      records,
      size: 2
    });

    const rendered = renderRuntimeCatalog(catalog);

    expect(rendered).toContain("Generated by pnpm board:lab:catalog");
    expect(rendered).toContain("id: \"duel-fair-official-v1\"");
    expect(rendered).toContain('boardConfigId: "standard-official-spiral"');
    expect(rendered).toContain("seeds: Object.freeze([30, 20])");
    expect(rendered.endsWith("\n")).toBe(true);
    expect(renderRuntimeCatalog(catalog)).toBe(rendered);
  });

  it.each([
    [{ ...manifest, status: "running" }, "complete"],
    [{ ...manifest, family: "freeform-random" }, "official-spiral"],
    [{ ...manifest, generatorVersion: "official-spiral-v2" }, "official-spiral-v1"],
    [{ ...manifest, evaluatorVersion: "duel-fair-v2" }, "duel-fair-v3"],
    [{ ...manifest, v3ProfileHash: null }, "v3ProfileHash"]
  ])("rejects an incompatible source manifest", (sourceManifest, message) => {
    expect(() => buildCatalog({
      catalogId: "duel-fair-official-v1",
      runId: "catalog-fixture",
      manifest: sourceManifest,
      records,
      size: 2
    })).toThrow(message);
  });

  it("rejects malformed ranked records", () => {
    expect(() => buildCatalog({
      catalogId: "duel-fair-official-v1",
      runId: "catalog-fixture",
      manifest,
      records: [{ ...records[0], boardHash: null }],
      size: 1
    })).toThrow("boardHash");
  });

  it("rejects a catalog larger than the distinct candidate pool", () => {
    expect(() => buildCatalog({
      catalogId: "duel-fair-official-v1",
      runId: "catalog-fixture",
      manifest,
      records,
      size: 4
    })).toThrow("requires 4 distinct ranked boards; found 3");
  });
});
